### ISSUE TITLE
Issue with SVG icons when using Rails/Webpacker.

### ISSUE THREAD

**Issue by jhirn** [quilljs/webpack-example#3]
Hello. I ran into the this issue when trying to use this guide with Rails 5.2/Webpacker 4.0. I assume I'm not the only person so I'll leave this here so the next person can benefit. 

Essentially in your `environment.js` you'll need to add the following. 
```
const fileLoader = environment.loaders.get('file')
fileLoader.exclude = /node_modules[\\/]quill/
```
This is because the file-loader will execute before the html-loader resulting in the svg data not being imported inline. 

I also did not need to import or register the snow theme. In fact doing so gave me a warning in the browser that I was redeclaring it.

**Comment by treglu** [comment]
Here is the final `environment.js` that works in my case:

```
const { environment } = require('@rails/webpacker')

const fileLoader = environment.loaders.get('file')
fileLoader.exclude = /node_modules[\\/]quill/

const svgLoader = {
    test: /\.svg$/,
    loader: 'svg-inline-loader'
  }
  
  environment.loaders.prepend('svg', svgLoader)

module.exports = environment
```

**Comment by phayes** [comment]
If you're using Vue with webpack, I fixed this by adding the following to my `chainWebpack` in `vue.config.js`. 

```js
  chainWebpack: (config) => {  
    // Get existing 'svg' rule and add negative query
    config.module
      .rule('svg')
      .resourceQuery({ not: [/raw/] }); // add negative query so that any svg import that ends in ?raw is ignored
    
    // Add raw loader for ?raw query parameter
    config.module
      .rule('raw_query')
      .resourceQuery(/raw$/) // match ?raw
      .use('raw-loader')
      .loader('raw-loader');
}
```
