### ISSUE TITLE
How to Import Full Toolbar?

### ISSUE THREAD

**Issue by gunjandatta** [quilljs/webpack-example#6]
Here is an attempt to import the library using this example. It's not rendering the toolbar as expected. How can you import and use only the Toolbar w/ all/most of the options?

```ts
import Quill from "quill/core";

// Modules
import Toolbar from "quill/modules/toolbar";

// Themes
import BubbleTheme from "quill/themes/bubble";
import Snow from "quill/themes/snow";

// Toolbar Components
import Blockquote from "quill/formats/blockquote"
import Bold from "quill/formats/bold";
import CodeBlock from "quill/formats/code";
import Italic from "quill/formats/italic";
import Header from "quill/formats/header";
import Image from "quill/formats/image";
import List from "quill/formats/list";
import Script from "quill/formats/script";
import Strike from "quill/formats/strike";
import Underline from "quill/formats/underline";
import Video from "quill/formats/video";

// Register the components
Quill.register({
    "modules/toolbar": Toolbar,
    "formats/blockquote": Blockquote,
    "formats/bold": Bold,
    "formats/code": CodeBlock,
    "formats/italic": Italic,
    "formats/header": Header,
    "formats/image": Image,
    "formats/list": List,
    "formats/script": Script,
    "formats/strike": Strike,
    "formats/underline": Underline,
    "formats/video": Video,
    "themes/bubble": BubbleTheme,
    "themes/snow": Snow
});

export default Quill;
```

![image](https://user-images.githubusercontent.com/18452035/180779122-a504f59f-bc63-4b65-b3e9-65a1b3f50ef9.png)

**Comment by sebastianwestberg** [comment]
HI @gunjandatta - I'm running into the exact same problem with `[object Module]` and missing icons. Did you ever solve this? Thanks in advance!
![Screenshot 2023-02-10 at 12 59 57](https://user-images.githubusercontent.com/4223277/218087462-ae0aa4de-62e6-4596-877c-42182beceee7.png)

**Comment by oliviasculley** [comment]
So it seems like this is caused by an incompatibility with `html-loader` attempting to use the new ES modules syntax. I was able to fix it by changing the webpack rule for `.svg`s like this:

```
        {
          test: /\.svg$/,
          loader: 'html-loader',
          options: {
            esModule: false
          }
        }
```

[This issue on webpack](https://github.com/webpack/webpack/issues/10053) and this [issue on html-loader](https://github.com/webpack-contrib/html-loader/issues/203) have more details. Hopefully this helps!
